### ISSUE TITLE
Prepare Homebrew formula (to be submitted to homebrew-core after release)

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/packetry#130]

**Comment by mossmann** [comment]
I have a basic, working formula. My plan is to release 0.1.0, then push the formula to an experimental tap (a repository containing the formula that makes it fairly convenient to use), invite folks to test it, and then push it upstream to homebrew-core after testing.

**Comment by mossmann** [comment]
I realized that there is likely more benefit from going through the upstream CI and review process than there would be from testing in our own tap, so I am skipping the tap and working on getting this merged upstream: https://github.com/Homebrew/homebrew-core/pull/177539

**Comment by martinling** [comment]
The Homebrew PR is now merged and it's possible to `brew install packetry`. :tada:
