### ISSUE TITLE
Packetry crashes when resizing

### ISSUE THREAD

**Issue by x0rloser** [greatscottgadgets/packetry#178]
Like the title says I can crash packetry by just resizing the main window.
This happens without opening any log or having any cynthion hw connected to my machine.
There is nothing printed to console if I start it from the console, and no msgboxes or anything are displayed.
The program just quits out immediately.

Done using packetry v0.2.1 release from git for Windows.
I am using Windows 11 x64 with all latest windows updates.
I do have multiple monitors, but it crashes even when I keep the bounds of the window within my main (middle) monitor.

Replication steps:
1) start packetry (either from windows start menu or from command line)
2) position mouse cursor on the bottom right corner until you see the "resize" mouse cursor show up.
3) click and hold the resize cursor the move the mouse anticlockwise circles like you are drawing a clockface, starting at the 12 at the top and moving thru the 9, 6, 3, and back to 12 again.
4) The program crashes and disappears for me everytime after 1 or 2 anticlockwise circles.

**Comment by x0rloser** [comment]
I tried this on the Linux build running on Ubuntu v22.04 and I cannot get it to crash.

**Comment by martinling** [comment]
If you run `packetry-cli` from the console, you should get some debug output, and also a backtrace if you run `set RUST_BACKTRACE=1` beforehand. My guess is that it will be some internal crash in GTK's Windows backend.

**Comment by x0rloser** [comment]
I did try with packetry-cli from console already and got no debug output.
I also tried just now after setting that env variable and also got no output.
Here are the commands i tried just in case I am doing something wrong:

```
C:\Program Files\Packetry\bin>set RUST_BACKTRACE=1
C:\Program Files\Packetry\bin>echo %RUST_BACKTRACE%
1
C:\Program Files\Packetry\bin>packetry-cli
C:\Program Files\Packetry\bin>
```

It returned to the comand prompt when the program crashed.

**Comment by mossmann** [comment]
@x0rloser Was this from the binary installer or compiled from source? Have you tried release 0.2.2?

I've been unable to reproduce the problem with 0.2.1 or 0.2.2 from the binary installer.

**Comment by martinling** [comment]
I'm also unable to reproduce this with the 0.2.2 installer.

**Comment by x0rloser** [comment]
I just tried with the v0.2.2 installer for windows from github releases page, and it still crashes in the same way.

Previously I had used the v0.2.1 installer for windows from the github releases page.

**Comment by martinling** [comment]
I haven't been able to try this on Windows with multiple monitors yet.

Are you able to reproduce this if you disconnect all but one monitor?

**Comment by martinling** [comment]
Also: are you able to reproduce this with any of the GTK example programs? I suspect that this is going to turn out to be a GTK bug that's specific to the Windows backend on multi-monitor systems.

**Comment by x0rloser** [comment]
I disabled all my monitors except one (via display settings -> disconnect this monitor), and set the remaining monitor to the standard "landscape" mode. I tested again and I get the same crash when resizing.

Are the GTK exmaple programs available anywhere prebuilt for windows? I don't have the time just now get a working gtk dev env sorted.

**Comment by martinling** [comment]
The [gvsbuild](https://github.com/wingtk/gvsbuild) project has [binary releases](https://github.com/wingtk/gvsbuild/releases) of the full GTK stack for Windows, but I've just checked and they don't include the example programs unfortunately.

**Comment by x0rloser** [comment]
thanks for the link - i've reported the issue there, and while it does seem somewhat nvidia driver related, im still hoping it will get fixed so i don't lose whatever i am doing in packetry due to reszing the window xD

**Comment by x0rloser** [comment]
I reported this issue to the gnome/gtk gitlab project.
It seems the problem is due to "NahimicOSD" dll, and is a known problem.

For more info see: https://gitlab.gnome.org/GNOME/gtk/-/issues/7003

The fix that worked for me was:

Open up services.msc as Admin, and scroll down to 'Nahimic service' ... right click 'Stop', and then right click 'Properties'.  While in the 'General' tab, make sure 'Startup type' says 'Disabled'.  Then in the 'Recovery' tab, make sure the 'recovery failures' are all set to 'Take No Action' . And then click OK when you are all set.  Click on the pictures below to see the whole image. Good luck !

After doing this it packetry no longer crashes for me during resizing.

For the record, I didn't have to reboot or anything after doing this.
