### ISSUE TITLE
ISO transfers all under single polling group.

### ISSUE THREAD

**Issue by AndrewCapon** [greatscottgadgets/packetry#186]
So I can see the order of my bulk transfers, the polling and then the "Unidentified transfer".

All my ISO packets though are contained in single "Polling" groups so I get something like : "Polling 89064 times for unidentified transfer on endpoint 36.3 OUT" and "Polling 89064 times for unidentified transfer on endpoint 36.3 IN".

If I expand the groups I see the transactions.

Why are these not displayed with the other transfers?
<img width="625" alt="Screenshot 2024-09-11 at 14 21 01" src="https://github.com/user-attachments/assets/ee95c83f-6abf-4701-a569-4d7dbad2a554">

**Comment by martinling** [comment]
This happens because the enumeration process wasn't captured, so Packetry hasn't seen the configuration descriptor request, which would include the endpoint descriptors in the response.

Without seeing the endpoint descriptors, Packetry doesn't know what the type of endpoint 2 is, so it describes transfers made on it as `unidentified`.

If you start the capture before you connect the device, you should get the descriptor tree in the devices pane, and these transfers should then be correctly identified.

**Comment by AndrewCapon** [comment]
Hi,

Thanks for the reply.

The device is being started after the capture has started though.

**Comment by AndrewCapon** [comment]
I also noticed not all the configurations are shown in the right pane, is this normal?

**Comment by martinling** [comment]
The single configuration being shown seems correct to me. The device descriptor has `bNumConfigurations` set to 1, indicating that there's only one configuration, and the host only requests that one descriptor.

The thing with isochronous transactions being shown in polling groups is a bug, though. I think the state machine is wrong here and it's expecting an ACK, which it shouldn't do in the isochronous case. I'll see about a fix.

**Comment by AndrewCapon** [comment]
Sorry used wrong word, I meant Alternate. So interface 1 alternate 0, interface 1 alternate 1, interface 1 alternate 2.

**Comment by martinling** [comment]
Yeah we may be doing something wrong there too. I'll take a look.

**Comment by martinling** [comment]
The issue with alternate interface settings is fixed in #189, which now includes a clip of your first capture as a test case.

![image](https://github.com/user-attachments/assets/efeeb2d7-65f1-4b1e-b1aa-f005a94759cb)

**Comment by AndrewCapon** [comment]
> The issue with alternate interface settings is fixed in #189, which now includes a clip of your first capture as a test case.
> 
> ![image](https://private-user-images.githubusercontent.com/673823/366926408-efeeb2d7-65f1-4b1e-b1aa-f005a94759cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNTMzODcsIm5iZiI6MTcyNjE1MzA4NywicGF0aCI6Ii82NzM4MjMvMzY2OTI2NDA4LWVmZWViMmQ3LTY1ZjEtNGIxZS1iMWFhLWYwMDVhOTQ3NTljYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQxNDU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YzRmMWM0ODAzN2VjMGFmYWFiNTgzMzQzMjg2ZDcxOGJlMmMxYWE4MzE3MmU1ZTIyMTU0ZDY2ZmQzNjE3Yjk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PqohtNLzdgqNP2L1S79Jm900vLthlAXM-CqRoII5NnU)

That's great, thanks for that :)

**Comment by AndrewCapon** [comment]
> I have some work in progress on fixing the isochronous transfers too, but that's going to take a bit longer to get right.
> 
> One of the more tricky issues involved is that in the case where we _haven't_ seen the endpoint descriptors, a transaction with just IN or OUT followed by DATA0 or DATA1 is ambiguous. It _could_ be a successful isochronous transaction, but it could also be an incomplete bulk/interrupt transaction that wasn't ACKed or NAKed by the host when it should have been.

Yeah. I see your point.

**Comment by martinling** [comment]
The issues with handling isochronous transactions are fixed in #192, which I'd appreciate your review on. I think that your two captures shared above are now interpreted correctly.

Note though that the result is not all that different - the isochronous transactions on each endpoint are still placed in one group, but that group is now labelled as an isochronous transfer rather than as a polling group.

**Comment by AndrewCapon** [comment]
Hi Martin,

Thanks very much for that.

So the iso transactions are not interspersed with say the bulk transactions? 

Thanks

Andy

**Comment by AndrewCapon** [comment]
Hi Martin, 

Thanks for the info, I wondered why all the SOFs were grouped, the same reason?

Looks like I am probably after the transaction or packet view.

I have gone back to using my old analyser, I will build and try your new version when I get a chance...

Thanks

Andy

**Comment by martinling** [comment]
> Thanks for the info, I wondered why all the SOFs were grouped, the same reason?

Yes, SOFs are gathered at two levels:
- Consecutive SOF packets on the wire, without other traffic in between are placed in a group equivalent to a transaction.
- All SOF groups in the capture are themselves placed in a group equivalent to a transfer.

The benefit of this becomes more obvious in the transaction view, or the interleaved view:
![image](https://github.com/user-attachments/assets/7a642b11-1fa4-47c9-9bce-50c3cf12a97b)

**Comment by AndrewCapon** [comment]
Sorry, I have been meaning to post here to say thanks for all the updates you have done. Packetry is so much more useful for me now. Nice job :)

**Comment by martinling** [comment]
Thanks!
