### ISSUE TITLE
Gateway is older (v0) than supported by this version of packeted (v1)

### ISSUE THREAD

**Issue by AndrewCapon** [greatscottgadgets/packetry#194]
Hi Guys,

I seem to get this when I first turn on the Cynthian and run packetry.

I have to run a `cynthion run analyzer` to program the fpga, then everything works.

Is this normal? Am I missing a way of getting the analyser into flash?

Thanks

Andy

**Comment by miek** [comment]
If you run `cynthion update` that should fix it.

**Comment by AndrewCapon** [comment]
Thanks very much :)
