### ISSUE TITLE
Minor issues installing on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by cristi-zz** [greatscottgadgets/packetry#44]
Tried to run packetry on Ubuntu 22.04.1 LTS.

There were some minor issues:

1) GTK 4 is not installed by default (tbh, I did an upgrade from 20.04 so maybe it comes by default for fresh installs?)
2) Need to install pcap libraries.

So in addition to official doc, I had to run:

    sudo apt-get install libgtk-4-dev gtk-4-examples libpcap-dev  

Then, the build went just fine.

Thank you!

LE: maybe gtk-4-examples is not needed, though.

**Comment by martinling** [comment]
Thanks for the report - I'll be updating the README soon so I'll add notes on these there.

You shouldn't need to install gtk-4-examples.
